### PR TITLE
create div.suggestions-wrapper

### LINKED ISSUE #27: add wrapper div to ul.suggestions to expand customization
For mapbox-gl-geocoder, we'd like to append a link to the results so that users can submit search feedback. This is a little tricky right now because if we append this element to ul.suggestions, it'll get cleared out as the user is typing. Given that ul.suggestions is best absolutely positioned, it's difficult to get this new element positioned where we want it (just below ul.suggestions).

@tristen what do you think about a wrapper div for ul.suggestions? From my testing it should be a fairly quick add - I'd be happy to make this PR. Also open to other suggestions!

cc @scottsfarley93

### PR DESCRIPTION
**Pull request by katydecorah**
fixes #27 

This PR adds div.suggestions-wrapper around ul.suggestions to extend customizations to the dropdown.

### CODE REVIEW

**Review by tristen — CHANGES_REQUESTED** [review]
Looks great! One thing: these two functions should probably target `wrapper` now: https://github.com/tristen/suggestions/blob/262b813beb95e91d97d35fa41828bba41a9bb6e5/src/list.js#L22-L28

**Comment by katydecorah** [comment]
> these two functions should probably target `wrapper` now

I didn't target `wrapper` on those two functions because if a query doesn't have results then, in our use case, we want div.suggestions-wrapper to continue to display so the user can still submit feedback. (The feedback link is appended to div.suggestions-wrapper.)

Do you think this implementation is too tightly coupled to our use case or do you think it would work in other implementations that you've seen?

**Comment by tristen** [comment]
Ahh gotcha! 

>  Do you think this implementation is too tightly coupled to our use case or do you think it would work in other implementations that you've seen?

Nahhh I think this works 👍

**Review by tristen — APPROVED** [review]
⚜️

**Pull request merged**
