### PR TITLE
Bumped version to 1.7.0

### PR DESCRIPTION
**Pull request by dburnsii**
Closed the previous pull request that included previous commits, created a new branch that bumps version to 1.7.0.

### CODE REVIEW

**Comment by tristen** [comment]
Thanks @dburnsii. One last thing: can you add an entry to [`CHANGELOG.md`](https://github.com/tristen/suggestions/blob/gh-pages/CHANGELOG.md) for this new version?

**Comment by dburnsii** [comment]
Should I update the `shard.lock` as well? Or is that handled by the CI?

**Comment by tristen** [comment]
👍 just this is great! thanks!

**Comment by tristen** [comment]
Published https://www.npmjs.com/package/suggestions

**Pull request merged**
